changesetBaseRefs:
  - HEAD

enableGlobalCache: false

nodeLinker: pnp

npmScopes:
  jsr:
    npmRegistryServer: 'https://npm.jsr.io'

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.10.2.cjs
